created dashboard screen
VanEvnglst/admin-dashboard pull request #6
Opened 2021-03-30 05:25 UTC by chelseaaxy

2021-04-03 10:19 UTC, VanEvnglst requested changes

2021-04-03 10:19 UTC, VanEvnglst commented on app/screens/dashboard/index.js
> +  React.useEffect(() => {
remove

2021-04-03 10:19 UTC, VanEvnglst commented on app/screens/dashboard/index.js
> +  const [newData, setnewData] = React.useState([
no need to use **useState** here. You can just define your dummy data on a separate file and import that here

2021-04-03 10:19 UTC, VanEvnglst commented on app/screens/dashboard/index.js
> +const Dashboard_Screen = ({ navigation }) => {
Change the name of the component here. You've already named the page as DashboardScreen. This will cause confusion to other developers.

2021-04-03 10:19 UTC, VanEvnglst commented on app/screens/dashboard/index.js
> +          <View style={{ alignItems: 'center', justifyContent: 'center', marginHorizontal: SIZES.base }}>
Define all your styles inside the **styles** file and use them here as needed. (e.g. styles.container)

2021-04-03 10:19 UTC, VanEvnglst commented on app/screens/dashboard/index.js
> +              <Text
Text component here shows nothing

2021-04-03 10:19 UTC, VanEvnglst commented on app/screens/dashboard/index.js
> +                  style={{
Refer to styles comment above and apply to all styles inside this file.

2021-04-03 10:19 UTC, VanEvnglst commented on app/screens/dashboard/index.js
> +                  />
Again your text component here shows nothing

2021-04-03 10:19 UTC, VanEvnglst commented on app/screens/dashboard/index.js
> +
Remove unnecessary spaces. Format files properly by right-clicking then choose _Format document_ option inside VS code

2021-04-03 10:19 UTC, VanEvnglst commented on app/screens/dashboard/styles.js
> +  TextViewStyle:
use camel case syntax when naming variables

2021-04-03 10:19 UTC, VanEvnglst commented on app/screens/dashboard/styles.js
> +};
Only define values you need. h1, h2, h4, body1, body2, body3 are all unused

2021-04-03 10:19 UTC, VanEvnglst commented on app/screens/dashboard/styles.js
> +};
No need to define this for now. The design we have is not that specific yet

2021-04-03 10:19 UTC, VanEvnglst commented on app/screens/dashboard/styles.js
> +const calendar_styles = StyleSheet.create({
use camel case when defining variables

2021-04-03 10:19 UTC, VanEvnglst commented on app/screens/dashboard/styles.js
> +      color: '#696969',
Make use of colors defined on top

2021-04-04 10:37 UTC, chelseaaxy commented
![image](https://user-images.githubusercontent.com/80298438/113505968-87adee80-9574-11eb-8773-9b79bd4214c7.png)
Good evening Sir, Okay lang po ba na na-force push ko po? Naggitpull naman po kaso ayaw pa rin po mapush. Pasensya na po ulit.

2021-04-11 06:29 UTC, VanEvnglst commented
@chelseaaxy yes this is fine. force push mo nalang

2021-04-12 06:02 UTC, merged